-- MySQL Script generated by MySQL Workbench
-- Mon Dec 11 16:27:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema poo_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema poo_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poo_project` DEFAULT CHARACTER SET utf8 ;
USE `poo_project` ;

-- -----------------------------------------------------
-- Table `poo_project`.`TB_CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poo_project`.`TB_CLIENTE` ;

CREATE TABLE IF NOT EXISTS `poo_project`.`TB_CLIENTE` (
  `idTB_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `NOME_CLIENTE` VARCHAR(255) NOT NULL,
  `CPF_CLIENTE` VARCHAR(20) NOT NULL,
  `EMAIL_CLIENTE` VARCHAR(45) NOT NULL,
  `ENDERECO_CLIENTE` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTB_CLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poo_project`.`TB_CATEGORIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poo_project`.`TB_CATEGORIA` ;

CREATE TABLE IF NOT EXISTS `poo_project`.`TB_CATEGORIA` (
  `idTB_CATEGORIA` INT NOT NULL AUTO_INCREMENT,
  `NOME_CAT` VARCHAR(255) NOT NULL,
  `DESCRICAO_CAT` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTB_CATEGORIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poo_project`.`TB_PRODUTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poo_project`.`TB_PRODUTO` ;

CREATE TABLE IF NOT EXISTS `poo_project`.`TB_PRODUTO` (
  `idTB_PRODUTO` INT NOT NULL AUTO_INCREMENT,
  `NOME_PRODUTO` VARCHAR(255) NOT NULL,
  `PRECO_PRODUTO` DOUBLE NOT NULL,
  `ESTOQUE_PRODUTO` INT NOT NULL,
  `TB_CATEGORIA_idTB_CATEGORIA` INT NOT NULL,
  PRIMARY KEY (`idTB_PRODUTO`, `TB_CATEGORIA_idTB_CATEGORIA`),
  INDEX `fk_TB_PRODUTO_TB_CATEGORIA1_idx` (`TB_CATEGORIA_idTB_CATEGORIA` ASC) VISIBLE,
  CONSTRAINT `fk_TB_PRODUTO_TB_CATEGORIA1`
    FOREIGN KEY (`TB_CATEGORIA_idTB_CATEGORIA`)
    REFERENCES `poo_project`.`TB_CATEGORIA` (`idTB_CATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poo_project`.`TB_FUNCIONARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poo_project`.`TB_FUNCIONARIO` ;

CREATE TABLE IF NOT EXISTS `poo_project`.`TB_FUNCIONARIO` (
  `idTB_FUNCIONARIO` INT NOT NULL AUTO_INCREMENT,
  `NOME_FUNCIONARIO` VARCHAR(255) NOT NULL,
  `ID_FUNCIONARIO` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`idTB_FUNCIONARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poo_project`.`TB_VENDA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poo_project`.`TB_VENDA` ;

CREATE TABLE IF NOT EXISTS `poo_project`.`TB_VENDA` (
  `idTB_VENDA` INT NOT NULL AUTO_INCREMENT,
  `DATA_VENDA` DATETIME NOT NULL,
  `VALORTOTAL_VENDA` DOUBLE NOT NULL,
  `QUANTIDADE` INT NOT NULL,
  `TB_PRODUTO_idTB_PRODUTO` INT NOT NULL,
  `TB_CLIENTE_idTB_CLIENTE` INT NULL,
  `TB_FUNCIONARIO_idTB_FUNCIONARIO` INT NULL,
  PRIMARY KEY (`idTB_VENDA`),
  UNIQUE KEY `unique_TB_VENDA` (`TB_CLIENTE_idTB_CLIENTE`, `TB_FUNCIONARIO_idTB_FUNCIONARIO`),
  INDEX `fk_TB_VENDA_TB_CLIENTE1_idx` (`TB_CLIENTE_idTB_CLIENTE` ASC),
  INDEX `fk_TB_VENDA_TB_FUNCIONARIO1_idx` (`TB_FUNCIONARIO_idTB_FUNCIONARIO` ASC),
  INDEX `fk_TB_PRODUTO_idTB_PRODUTO1_idx` (`TB_PRODUTO_idTB_PRODUTO` ASC),
  CONSTRAINT `fk_TB_VENDA_TB_CLIENTE1`
    FOREIGN KEY (`TB_CLIENTE_idTB_CLIENTE`)
    REFERENCES `poo_project`.`TB_CLIENTE` (`idTB_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_VENDA_TB_FUNCIONARIO1`
    FOREIGN KEY (`TB_FUNCIONARIO_idTB_FUNCIONARIO`)
    REFERENCES `poo_project`.`TB_FUNCIONARIO` (`idTB_FUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_PRODUTO_idTB_PRODUTO1`
    FOREIGN KEY (`TB_PRODUTO_idTB_PRODUTO`)
    REFERENCES `poo_project`.`TB_PRODUTO` (`idTB_PRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Inserir dados fictícios para TB_CLIENTE
INSERT INTO `poo_project`.`TB_CLIENTE` (`NOME_CLIENTE`, `CPF_CLIENTE`, `EMAIL_CLIENTE`, `ENDERECO_CLIENTE`)
VALUES 
('João Silva', '123.456.789-01', 'joao@email.com', 'Rua A, 123'),
('Maria Oliveira', '987.654.321-00', 'maria@email.com', 'Avenida B, 456'),
('Carlos Santos', '111.222.333-44', 'carlos@email.com', 'Rua C, 789');

-- Inserir dados fictícios para TB_CATEGORIA
-- Inserir dados fictícios para TB_CATEGORIA
INSERT INTO `poo_project`.`TB_CATEGORIA` (`NOME_CAT`, `DESCRICAO_CAT`)
VALUES 
('Processadores', 'Componentes de hardware'),
('Fontes', 'Componentes de hardware'),
('Placas de Vídeo', 'Componentes de hardware'),
('Placa Mae', 'Componentes de hardware'),
('Memoria RAM', 'Componentes de hardware'),
('HD/SSD', 'Componentes de hardware');

-- Inserir dados fictícios para TB_PRODUTO
INSERT INTO `poo_project`.`TB_PRODUTO` (`NOME_PRODUTO`, `PRECO_PRODUTO`, `ESTOQUE_PRODUTO`, `TB_CATEGORIA_idTB_CATEGORIA`)
VALUES 
('AMD Ryzen 5 3600', 1241.00, 13, 1),
('AMD Ryzen 7 5800X', 1490.00, 18, 1),
('Intel Core i5-10400F', 600.00, 16, 1),
('Intel Core i7-10700K', 1500.00, 14, 1),
('Intel Core i9-10900K', 1800.00, 12, 1),
('Aerocool 400W KCAS', 194, 10, 2),
('Fortrek Black Hawk', 238, 17, 2),
('AMD Radeon RX 7600', 1900.00, 13, 3),
('AMD Radeon RX 6600', 1140.00, 15, 3),
('Nvidia MSI RTX 3050', 1580.00, 18, 3),
('NVIDIA GeForce GTX 1660', 1350.00, 10, 3),
('ASRock B450M Steel Legend', 1092.00, 13, 4),
('Gigabyte A320M-S2H', 736.00, 6, 4),
('ASUS Prime - H510M', 555.00, 7, 4),
('KINGSTON FURY BEAST DDR4 8GB 3200 MHZ', 150.00, 15, 5),
('Corsair Vengeance LPX DDR4 - 16GB (2x 8GB)', 370.00, 8, 5),
('ADATA XPG Hunter DDR5 16GB 5200 MHz', 236.68, 10, 5),
('SSD 1 TB Kingston NV2 M.2 2280 PCIe', 300.00, 9, 6),
('SSD 960 GB Kingston A400 SATA', 295.00, 11, 6),
('HD WD Blue 1TB 3.5"', 250.00, 12, 6);


-- Inserir dados fictícios para TB_FUNCIONARIO
INSERT INTO `poo_project`.`TB_FUNCIONARIO` (`NOME_FUNCIONARIO`, `ID_FUNCIONARIO`)
VALUES 
('Rodrigo Silva', '1807'),
('Renan Pereira', 'A987');

-- Inserir dados fictícios para TB_VENDA
INSERT INTO `poo_project`.`TB_VENDA` (`DATA_VENDA`, `VALORTOTAL_VENDA`, `QUANTIDADE`, `TB_PRODUTO_idTB_PRODUTO`, `TB_CLIENTE_idTB_CLIENTE`, `TB_FUNCIONARIO_idTB_FUNCIONARIO`)
VALUES 
('2023-12-13 10:30:00', 1500.00, 2, 1, 1, 1),
('2023-12-13 11:45:00', 50.00, 5, 2, 2, 2);
